230505210716 from main.py: Loading new instance...
230505210716 from main.py: setting GTK requirements...
230505210716 from main.py: GTK ready...
230505210716 from main.py: Loading settings file...
230505210716 from main.py: Connecting globals...
230505210716 from main.py: 4
230505210716 from main.py: Finished main class preamble...
230505210716 from main.py: Starting Class LoggixMain()...
230505210716 from main.py around line 149: Initialization error: g-file-error-quark: Failed to open file “/home/ace/Documents/GitHub/LoggiX/assets/UI/LoggiX_UI_2.0.XML”: No such file or directory (4) 
 A controlled shutdown was preformed...
230505210746 from main.py: Loading new instance...
230505210746 from main.py: setting GTK requirements...
230505210746 from main.py: GTK ready...
230505210746 from main.py: Loading settings file...
230505210746 from main.py: Connecting globals...
230505210746 from main.py: 4
230505210746 from main.py: Finished main class preamble...
230505210746 from main.py: Starting Class LoggixMain()...
230505210746 from main.py: contest mode enabled by user
230505210746 from main.py: contest mode enabled by user
230505210746 from main.py around line 287: Non-fatal error while trying to calculate total pages for GUI do display: 'NoneType' object has no attribute 'split'
230505210746 from main.py: Software started. Running from: /home/ace/Documents/GitHub/LoggiX

230505211105 from main.py: Loading new instance...
230505211105 from main.py: setting GTK requirements...
230505211105 from main.py: GTK ready...
230505211105 from main.py: Loading settings file...
230505211105 from main.py: Connecting globals...
230505211105 from main.py: 4
230505211105 from main.py: Finished main class preamble...
230505211105 from main.py: Starting Class LoggixMain()...
230505211106 from main.py: contest mode enabled by user
230505211106 from main.py: contest mode enabled by user
230505211106 from main.py: Software started. Running from: /home/ace/Documents/GitHub/LoggiX

230505211139 from main.py: Loading new instance...
230505211139 from main.py: setting GTK requirements...
230505211139 from main.py: GTK ready...
230505211139 from main.py: Loading settings file...
230505211139 from main.py: Connecting globals...
230505211139 from main.py: 4
230505211139 from main.py: Finished main class preamble...
230505211139 from main.py: Starting Class LoggixMain()...
230505211139 from main.py: contest mode enabled by user
230505211139 from main.py: contest mode enabled by user
230505211139 from main.py: Software started. Running from: /home/ace/Documents/GitHub/LoggiX

230519183406 from main.py: Loading new instance...
230519183406 from main.py: setting GTK requirements...
230519183406 from main.py: GTK ready...
230519183406 from main.py: Loading settings file...
230519183406 from main.py: Connecting globals...
230519183406 from main.py: 4
230519183406 from main.py: Failed to predefine globals. error: [Errno 2] No such file or directory: '/home/ace/.local/share/applications/LoggiX/assets/contacts.hlfv2'
230519183406 from main.py: This might be due to an invalid file path in your settings file. are they all correct?
230519183406 from main.py: Software closing with dignity.
230519183411 from main.py: Loading new instance...
230519183411 from main.py: setting GTK requirements...
230519183411 from main.py: GTK ready...
230519183411 from main.py: Loading settings file...
230519183411 from main.py: Connecting globals...
230519183411 from main.py: 4
230519183411 from main.py: Failed to predefine globals. error: [Errno 2] No such file or directory: '/home/ace/.local/share/applications/LoggiX/assets/contacts.hlfv2'
230519183411 from main.py: This might be due to an invalid file path in your settings file. are they all correct?
230519183411 from main.py: Software closing with dignity.
230519183412 from main.py: Loading new instance...
230519183412 from main.py: setting GTK requirements...
230519183412 from main.py: GTK ready...
230519183412 from main.py: Loading settings file...
230519183412 from main.py: Connecting globals...
230519183412 from main.py: 4
230519183412 from main.py: Failed to predefine globals. error: [Errno 2] No such file or directory: '/home/ace/.local/share/applications/LoggiX/assets/contacts.hlfv2'
230519183412 from main.py: This might be due to an invalid file path in your settings file. are they all correct?
230519183412 from main.py: Software closing with dignity.
230519183412 from main.py: Loading new instance...
230519183412 from main.py: setting GTK requirements...
230519183412 from main.py: GTK ready...
230519183412 from main.py: Loading settings file...
230519183412 from main.py: Connecting globals...
230519183412 from main.py: 4
230519183412 from main.py: Failed to predefine globals. error: [Errno 2] No such file or directory: '/home/ace/.local/share/applications/LoggiX/assets/contacts.hlfv2'
230519183412 from main.py: This might be due to an invalid file path in your settings file. are they all correct?
230519183412 from main.py: Software closing with dignity.
230519183413 from main.py: Loading new instance...
230519183413 from main.py: setting GTK requirements...
230519183413 from main.py: GTK ready...
230519183413 from main.py: Loading settings file...
230519183413 from main.py: Connecting globals...
230519183413 from main.py: 4
230519183413 from main.py: Failed to predefine globals. error: [Errno 2] No such file or directory: '/home/ace/.local/share/applications/LoggiX/assets/contacts.hlfv2'
230519183413 from main.py: This might be due to an invalid file path in your settings file. are they all correct?
230519183413 from main.py: Software closing with dignity.
230519183413 from main.py: Loading new instance...
230519183413 from main.py: setting GTK requirements...
230519183413 from main.py: GTK ready...
230519183413 from main.py: Loading settings file...
230519183413 from main.py: Connecting globals...
230519183413 from main.py: 4
230519183413 from main.py: Failed to predefine globals. error: [Errno 2] No such file or directory: '/home/ace/.local/share/applications/LoggiX/assets/contacts.hlfv2'
230519183413 from main.py: This might be due to an invalid file path in your settings file. are they all correct?
230519183413 from main.py: Software closing with dignity.
230519183557 from main.py: Loading new instance...
230519183557 from main.py: setting GTK requirements...
230519183557 from main.py: GTK ready...
230519183557 from main.py: Loading settings file...
230519183557 from main.py: Connecting globals...
230519183557 from main.py: 4
230519183557 from main.py: Failed to predefine globals. error: [Errno 2] No such file or directory: '/home/ace/.local/share/applications/LoggiX/assets/contacts.hlfv2'
230519183557 from main.py: This might be due to an invalid file path in your settings file. are they all correct?
230519183557 from main.py: Software closing with dignity.
230519183840 from main.py: Loading new instance...
230519183840 from main.py: setting GTK requirements...
230519183840 from main.py: GTK ready...
230519183840 from main.py: Loading settings file...
230519183840 from main.py: Connecting globals...
230519183840 from main.py: 4
230519183840 from main.py: Finished main class preamble...
230519183840 from main.py: Starting Class LoggixMain()...
230519183840 from main.py: contest mode enabled by user
230519183840 from main.py: contest mode enabled by user
230519183840 from main.py: Software started. Running from: /home/ace/Documents/GitHub/LoggiX

230519183949 from main.py: contest mode disabled by user
230519183949 from main.py: contest mode enabled by user
230521113855 from main.py: Loading new instance...
230521113855 from main.py: setting GTK requirements...
230521113855 from main.py: GTK ready...
230521113855 from main.py: Loading settings file...
230521113855 from main.py: Connecting globals...
230521113855 from main.py: 4
230521113855 from main.py: Finished main class preamble...
230521113855 from main.py: Starting Class LoggixMain()...
230521113855 from main.py: contest mode enabled by user
230521113855 from main.py: contest mode enabled by user
230521113855 from main.py: Software started. Running from: /home/ace/Documents/GitHub/LoggiX

230521113915 from main.py: contest mode disabled by user
230521113916 from main.py: contest mode enabled by user
230521113916 from main.py: contest mode disabled by user
230521113917 from main.py: contest mode enabled by user
230521113918 from main.py: contest mode disabled by user
230521125222 from main.py: Loading new instance...
230521125222 from main.py: setting GTK requirements...
230521125222 from main.py: GTK ready...
230521125222 from main.py: Loading settings file...
230521125222 from main.py: Connecting globals...
230521125222 from main.py: 4
230521125222 from main.py: Finished main class preamble...
230521125222 from main.py: Starting Class LoggixMain()...
230521125222 from main.py: contest mode enabled by user
230521125222 from main.py: contest mode enabled by user
230521125222 from main.py: Software started. Running from: /home/ace/Documents/GitHub/LoggiX

230528213709 from main.py: Loading new instance...
230528213709 from main.py: setting GTK requirements...
230528213709 from main.py: GTK ready...
230528213709 from main.py: Loading settings file...
230528213709 from main.py: Connecting globals...
230528213709 from main.py: 4
230528213709 from main.py: Finished main class preamble...
230528213709 from main.py: Starting Class LoggixMain()...
230528213709 from main.py: contest mode enabled by user
230528213709 from main.py: contest mode enabled by user
230528213709 from main.py: Software started. Running from: /home/ace/Documents/GitHub/LoggiX

230528214105 from main.py: Loading new instance...
230528214105 from main.py: setting GTK requirements...
230528214105 from main.py: GTK ready...
230528214105 from main.py: Loading settings file...
230528214105 from main.py: Connecting globals...
230528214105 from main.py: 4
230528214105 from main.py: Finished main class preamble...
230528214105 from main.py: Starting Class LoggixMain()...
230528214105 from main.py: contest mode enabled by user
230528214105 from main.py: contest mode enabled by user
230528214105 from main.py: Software started. Running from: /home/ace/Documents/GitHub/LoggiX

230529122710 from main.py: Loading new instance...
230529122710 from main.py: setting GTK requirements...
230529122710 from main.py: GTK ready...
230529122710 from main.py: Loading settings file...
230529122710 from main.py: Connecting globals...
230529122710 from main.py: 4
230529122710 from main.py: Finished main class preamble...
230529122710 from main.py: Starting Class LoggixMain()...
230529122710 from main.py: contest mode enabled by user
230529122710 from main.py: contest mode enabled by user
230529122710 from main.py: Software started. Running from: /home/ace/Documents/GitHub/LoggiX

